import jsPDF from 'jspdf';

export function generateCVPDF(cvData, analysis) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPos = 20;

  // Title
  doc.setFontSize(24);
  doc.setFont(undefined, 'bold');
  doc.text('CV Analysis Report', margin, yPos);
  yPos += 15;

  // Date
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, yPos);
  yPos += 15;

  // Personal Information
  if (cvData.name) {
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Personal Information', margin, yPos);
    yPos += 10;

    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    doc.text(`Name: ${cvData.name}`, margin, yPos);
    yPos += 7;
  }

  if (cvData.email) {
    doc.text(`Email: ${cvData.email}`, margin, yPos);
    yPos += 7;
  }

  if (cvData.phone) {
    doc.text(`Phone: ${cvData.phone}`, margin, yPos);
    yPos += 10;
  }

  // Skills
  if (cvData.skills && cvData.skills.length > 0) {
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Skills', margin, yPos);
    yPos += 10;

    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    const skillsText = cvData.skills.join(', ');
    const splitSkills = doc.splitTextToSize(skillsText, pageWidth - 2 * margin);
    doc.text(splitSkills, margin, yPos);
    yPos += splitSkills.length * 7 + 10;
  }

  // Analysis Summary
  if (analysis) {
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Analysis Summary', margin, yPos);
    yPos += 10;

    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    
    if (analysis.summary) {
      const summaryLines = doc.splitTextToSize(analysis.summary, pageWidth - 2 * margin);
      doc.text(summaryLines, margin, yPos);
      yPos += summaryLines.length * 7 + 10;
    }
  }

  // Experience
  if (cvData.experience && cvData.experience.length > 0) {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Experience', margin, yPos);
    yPos += 10;

    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    
    cvData.experience.forEach((exp, idx) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFont(undefined, 'bold');
      doc.text(`${exp.title || 'Position'}`, margin, yPos);
      yPos += 7;
      
      doc.setFont(undefined, 'normal');
      if (exp.company) {
        doc.text(`Company: ${exp.company}`, margin, yPos);
        yPos += 7;
      }
      if (exp.duration) {
        doc.text(`Duration: ${exp.duration}`, margin, yPos);
        yPos += 7;
      }
      yPos += 5;
    });
  }

  // Education
  if (cvData.education && cvData.education.length > 0) {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Education', margin, yPos);
    yPos += 10;

    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    
    cvData.education.forEach((edu, idx) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }

      doc.text(`${edu.degree || edu.qualification || 'Education'}`, margin, yPos);
      yPos += 7;
      
      if (edu.institution) {
        doc.text(`Institution: ${edu.institution}`, margin, yPos);
        yPos += 7;
      }
      if (edu.year) {
        doc.text(`Year: ${edu.year}`, margin, yPos);
        yPos += 7;
      }
      yPos += 5;
    });
  }

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(9);
  doc.setTextColor(128);
  doc.text('Generated by FutureLinked ZA - www.futurelinked.co.za', pageWidth / 2, footerY, { align: 'center' });

  return doc;
}

export function downloadCVPDF(cvData, analysis) {
  const doc = generateCVPDF(cvData, analysis);
  doc.save(`CV_Analysis_${new Date().toISOString().split('T')[0]}.pdf`);
}

export function printCV(cvData, analysis) {
  const doc = generateCVPDF(cvData, analysis);
  doc.autoPrint();
  window.open(doc.output('bloburl'), '_blank');
}
